version: '3.9'
services:
  queue:
    build: .
    entrypoint: '/www/entrypoint.sh'
    volumes:
      - "./:/www"

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
