version: '3.9'
services:
  queue:
    build: .
    image: di-kay/email:0.0.2
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: 24d6a6bac71acf
      MAIL_PASSWORD: a50c4a6fcf6815
      KAFKA_PARTITION: 1
      KAFKA_BROKERS: pkc-z1o60.europe-west1.gcp.confluent.cloud:9092
      KAFKA_USERNAME: DH5TYVGN2OW4OGG5
      KAFKA_PASSWORD: bshBigTF6B8DDRHLs+OWbEYwyZ39Fp7BfZfHg3f/52BxhSzgVBfTTUGQkO+f+1m5
      KAFKA_MECHANISM: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_QUEUE: email
      KAFKA_OFFSET_RESET: latest
    command: 'php artisan queue:work'
