apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-backend
  template:
    metadata:
      labels:
        io.kompose.network/ambassador-default: "true"
        io.kompose.service: ambassador-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan serve --host=0.0.0.0
          env:
            - name: CACHE_DRIVER
              value: redis
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ambassador-secrets
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ambassador-secrets
                  key: DB_PASSWORD
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_AMBASSADOR_QUEUE
              value: ambassador
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_CHECKOUT_QUEUE
              value: checkout
            - name: KAFKA_EMAIL_QUEUE
              value: email
            - name: KAFKA_MECHANISM
              value: PLAIN
            - name: KAFKA_OFFSET_RESET
              value: latest
            - name: KAFKA_PARTITION
              value: "1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_QUEUE
              value: default
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: QUEUE_CONNECTION
              value: kafka
            - name: REDIS_HOST
              value: redis
            - name: USER_MICROSERVICE_HOST
              value: users-backend:8001/api
          image: di-kay/ambassador:0.0.1
          name: ambassador-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador_backend
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8000
  selector:
    io.kompose.service: ambassador-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-queue
  name: ambassador-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-queue
  template:
    metadata:
      labels:
        io.kompose.network/ambassador-default: "true"
        io.kompose.service: ambassador-queue
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan queue:work
          env:
            - name: CACHE_DRIVER
              value: file
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value: 34.159.44.201
            - name: DB_PASSWORD
              value: (dhNIeQ.8xVt^-1\
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_AMBASSADOR_QUEUE
              value: ambassador
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key:
                    KAFKA_BROKERS
            - name: KAFKA_CHECKOUT_QUEUE
              value: checkout
            - name: KAFKA_EMAIL_QUEUE
              value: email
            - name: KAFKA_MECHANISM
              value: PLAIN
            - name: KAFKA_OFFSET_RESET
              value: latest
            - name: KAFKA_PARTITION
              value: "1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_QUEUE
              value: default
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: QUEUE_CONNECTION
              value: kafka
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: USER_MICROSERVICE_HOST
              value: http://users_backend:8000/api
          image: di-kay/ambassador:0.0.1
          name: ambassador-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
