apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-backend
  template:
    metadata:
      labels:
        io.kompose.network/checkout-default: "true"
        io.kompose.service: checkout-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan serve --host=0.0.0.0
          env:
            - name: CHECKOUT_URL
              value: http://localhost:5000
            - name: DB_DATABASE
              value: checkout
            - name: DB_HOST
              value: 35.198.76.136
            - name: DB_PASSWORD
              value: (dhNIeQ.8xVt^-1\
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_ADMIN_QUEUE
              value: admin
            - name: KAFKA_AMBASSADOR_QUEUE
              value: ambassador
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_EMAIL_QUEUE
              value: email
            - name: KAFKA_MECHANISM
              value: PLAIN
            - name: KAFKA_OFFSET_RESET
              value: latest
            - name: KAFKA_PARTITION
              value: "1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_QUEUE
              value: checkout
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: QUEUE_CONNECTION
              value: kafka
            - name: STRIPE_SECRET
              value: sk_test_51NvEYWI46FFwFAHY0kKaFA8KBybVihTO6tsf3nPgplYfCJbpRYfQU9f4BEIk3O40CX9Hcu6coxdYsbCymPMyuQOT00NLo8t1Lt
            - name: USER_MICROSERVICE_HOST
              value: users-backend:8001/api
          image: di-kay/checkout:0.0.1
          name: checkout-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
    io.kompose.service: checkout-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-queue
  name: checkout-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-queue
  template:
    metadata:
      labels:
        io.kompose.network/checkout-default: "true"
        io.kompose.service: checkout-queue
    spec:
      containers:
        - args:
            - sh
            - -c
            - php artisan config:cache && php artisan queue:work
          env:
            - name: CHECKOUT_URL
              value: http://localhost:5000
            - name: DB_DATABASE
              value: checkout
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: checkout-secrets
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: checkout-secrets
                  key: DB_PASSWORD
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: KAFKA_ADMIN_QUEUE
              value: admin
            - name: KAFKA_AMBASSADOR_QUEUE
              value: ambassador
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_EMAIL_QUEUE
              value: email
            - name: KAFKA_MECHANISM
              value: PLAIN
            - name: KAFKA_OFFSET_RESET
              value: latest
            - name: KAFKA_PARTITION
              value: "1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_QUEUE
              value: checkout
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: QUEUE_CONNECTION
              value: kafka
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: checkout-secrets
                  key: STRIPE_SECRET
            - name: USER_MICROSERVICE_HOST
              value: http://users_backend:8000/api
          image: di-kay/checkout:0.0.1
          name: checkout-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
