apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: email-queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: email-queue
  template:
    metadata:
      labels:
        io.kompose.network/email-default: "true"
        io.kompose.service: email-queue
    spec:
      containers:
        - args:
            - php
            - artisan
            - queue:work
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKERS
            - name: KAFKA_MECHANISM
              value: PLAIN
            - name: KAFKA_OFFSET_RESET
              value: latest
            - name: KAFKA_PARTITION
              value: "1"
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_PASSWORD
            - name: KAFKA_QUEUE
              value: email
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_USERNAME
            - name: MAIL_HOST
              value: sandbox.smtp.mailtrap.io
            - name: MAIL_MAILER
              value: smtp
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_PORT
              value: "2525"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: MAIL_USERNAME
          image: di-kay/email:0.0.2
          name: email-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"