version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/www"
    depends_on:
      - db
    entrypoint: /bin/sh -c "cd /www && composer i && php artisan serve --host=0.0.0.0"
    networks:
      - default
      - users

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "33066:3306"
    networks:
      - default

volumes:
  database:

networks:
  users:
    name: users_default
  default:
