version: '3.9'
services:
  checkout_backend:
    build: .
    image: di-kay/checkout:0.0.1
    ports:
      - "8002:8000"
    command: sh -c "php artisan config:cache && php artisan serve --host=0.0.0.0"
    environment:
      KAFKA_PARTITION: 1
      KAFKA_BROKERS: pkc-z1o60.europe-west1.gcp.confluent.cloud:9092
      KAFKA_USERNAME: DH5TYVGN2OW4OGG5
      KAFKA_PASSWORD: bshBigTF6B8DDRHLs+OWbEYwyZ39Fp7BfZfHg3f/52BxhSzgVBfTTUGQkO+f+1m5
      KAFKA_MECHANISM: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_QUEUE: checkout
      KAFKA_OFFSET_RESET: latest
      KAFKA_EMAIL_QUEUE: email
      KAFKA_AMBASSADOR_QUEUE: ambassador
      KAFKA_ADMIN_QUEUE: admin
      QUEUE_CONNECTION: kafka
      USER_MICROSERVICE_HOST: http://users_backend:8000/api
      DB_HOST: 35.198.76.136
      DB_PORT: 3306
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: (dhNIeQ.8xVt^-1\
      STRIPE_SECRET: sk_test_51NvEYWI46FFwFAHY0kKaFA8KBybVihTO6tsf3nPgplYfCJbpRYfQU9f4BEIk3O40CX9Hcu6coxdYsbCymPMyuQOT00NLo8t1Lt
      CHECKOUT_URL: http://localhost:5000

  checkout_queue:
    build: .
    image: di-kay/checkout:0.0.1
    command: sh -c "php artisan config:cache && php artisan queue:work"
    environment:
      KAFKA_PARTITION: 1
      KAFKA_BROKERS: pkc-z1o60.europe-west1.gcp.confluent.cloud:9092
      KAFKA_USERNAME: DH5TYVGN2OW4OGG5
      KAFKA_PASSWORD: bshBigTF6B8DDRHLs+OWbEYwyZ39Fp7BfZfHg3f/52BxhSzgVBfTTUGQkO+f+1m5
      KAFKA_MECHANISM: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_QUEUE: checkout
      KAFKA_OFFSET_RESET: latest
      KAFKA_EMAIL_QUEUE: email
      KAFKA_AMBASSADOR_QUEUE: ambassador
      KAFKA_ADMIN_QUEUE: admin
      QUEUE_CONNECTION: kafka
      USER_MICROSERVICE_HOST: http://users_backend:8000/api
      DB_HOST: 35.198.76.136
      DB_PORT: 3306
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: (dhNIeQ.8xVt^-1\
      STRIPE_SECRET: sk_test_51NvEYWI46FFwFAHY0kKaFA8KBybVihTO6tsf3nPgplYfCJbpRYfQU9f4BEIk3O40CX9Hcu6coxdYsbCymPMyuQOT00NLo8t1Lt
      CHECKOUT_URL: http://localhost:5000
